name: RayTracer

library:
  source-dirs: src

executables:
  projectileSimulator:
    main: Main.hs
    source-dirs:
      - app/projectileSimulator
    dependencies:
      - RayTracer

tests:
  RayTracer-tests:
    main: Spec.hs
    source-dirs: spec
    dependencies:
      - RayTracer

dependencies:
  - base
  - array
  - hspec